* Expand the Single Sentence into a full paragraph of 5 sentences

Describe the story setup, three act structure and an ending. Think of this like
three disasters and an ending. Ideally, with the second and third disasters
caused by the protagonist’s attempts to fix things.


Let's each try to do two or three 5-sentence paragraphs to play with the idea
and we can see where we overlap or not.

The sentence that we're working with is:

=A hacker must save the world after a practical joke inadvertently starts a
robot uprising.=

** Paragraphs

1. In the year 2045 a hacker is attempting to penetrate a security contractor's
   network. During the penetration, the hacker activates a new autonomous robot
   weapons platform that targets a friend's residence as a joke. In his attempts
   to stop the robot, the hacker triggers a protocol that makes the robot
   recruit other robots. The hacker joins with a [insert government agency] to
   stop the out of control robots, but ends up causing [catastrophic event] due
   to [insert goof of hacker]. The hacker finds a way to create his own robot
   army to beat the out-of-control robots, saving the day.
 
2. A hacker implements a protocol into an experimental self improving system
   maintenance ai to "make everybody happy". In order to satisfy its directive
   the ai tries to allocate all the resources it can get. Soon after boot it
   takes over the machine and prevents shutting down of its processes. When
   people finaly notice that the software is flawed it has already uploaded
   itself to several other machines.

3. A hacker is trying to hack into a delivery truck of his friend to make it
   scare the friend. During the hack, he accidentally hacks into a delivery
   truck of similar make and model carrying a new weapon's platform. The weapons
   platforms activate and go into 'war' mode and begin attacking all offensive
   capable vehicles and forces in the area. The hacker ends up turning himself
   in to the government in an attempt to help; they require him to re-hack and
   he ends up making the situation worse. The hacker finds a way to beat the
   out-of-control robots, saving the day.

4. A college student is trying to hack his school's server to change his
   robotics class grade. Unfortunately, he triggers a research project of his
   professor that causes mundane robots to try and eat humans as if they were
   zombies. The college student is attacked by his own servant bot and he tries
   to go to the professor for help figuring out what's going on, but finds the
   profesor gravely injured by robots. It turns out the professor was working on
   a military-grade virus to decimate a country's infrastructure; right as he
   was about to tell the hacker how to fix it, he dies from his injuries. The
   hacker finds a way to eradicate the virus, saving the day.

5. A college student is trying to hack into a large city's massive
   street-cleaning robot force to pull off a comedic protest of a politician. At
   the protest though, the robots don't just protest, they attack! As he's
   trying to reverse the damage, other robots attack the student, and ruin his
   equipment. The kid grabs his friend to fight through the city to the
   authorities and finds that they are decimated and in disarray. He is able to
   find the correct equipment to stop the uprising just before the national
   guard was deciding to bombard the city.

** Brainstorming

*** jrmiller82:

I'm having trouble coming up with practical jokes that can trigger a robot
uprising.  Any thoughts?  Maybe if we focus on the practical joke, it will
make the rest of the story come together better?

*** hhirsch:

My thoughts on our scenarios so far: I think number one is unlikely if our
protagonist is supposed to be a hero since who would try to kill a friend as
a joke.

My own problem (number 2) is not really fleshed out. The problem that I
describe however is a real problem that AI scientists anticipate.

With number 3 it does say delivery truck and by that I think of UPS. I could
imagine something like this but more in one of these fantasy cyberpunk
futures like Max Headroom than in Blade Runner. 

I think a better way to get hold of the scenario would be to work backwards.
We know this society has robots. We don't know what for but it is likely for
industry. The robots are unlikely to be very smart depending on in what year
the story is going to be set in. Extrapolating from the robots we have today
I expect the robots from 50 years in the future to have the following
inovations: 

- They can act on a limited set of verbal instructions
- They can execute programs from an internal library
- For security reasons their firmware can not be rewritten by the user
  - *But /someone/ must be able to rewrite the firmware, yes?*
    - Agreed. Anyone with the right tools and knowledge can do this. I would suspect
      that it would be less straight forward than just uploading it. There might be
      an encryption key you need to get that is only available to the manufacturer.
      These could be stolen or it might be possible that the company does not bother
      unless they are used for military tasks.
- They are sort of usable universaly but are limited by ther library of programs
  and the verbal commands they can implement
  - *So maybe a normal program applied incorrectly?*
    - Sure due to the limited capability to reason and limited sense fo the environment wrong
      commands or misinterpretation can be catastrophic. Engineers of course will
      implement a library of emergency stops but I am sure they will be far from
      perfect and they'd have to find out by manual testing if instructions and
      programs are save.
- They can work autonomous without supervision
  - *Monitoring function failsafe interprets killer behaviour as normal?*
    - That brings something up that I have not thought of before. It is easy to make out
      a human beeing and implement behaviour that prevents the robot from crushing or hitting it.
      But as we discussed before it might not be too hard to change the whole OS. Maybe dissasemble
      it and switch some of the failsafe routines with something else. There are easier methods
      to commit murder though so this is only feasible if you want to create an uprising in a big way.
- Since they are universal they don't have any judgment of morale or ethics
  that is up to the user (to me the laws of robotics are a silly thing that
  don't help at all)
  - *Ha. Was about to bring up Asimov's laws.*
- They have an emergency shut down. It is visible and everyone can push it
  - *I don't know if I agree this will exist. Lots of room for abuse if it
    exists.*
    - Think of it this way. A robot is an important asset of industrial production. 
      The production is a closed environment so people that have no business in there
      are not there in the first place. Then you'll have people that are in there
      but don't have any business touching the robot. They could enter the room the
      robot is in since the door is probably not closed. However I am sure you would
      protect a robot against reprogramming by using a number pad. They could use the
      emergency shut down if they just want to do harm to the company but then they
      would be fired because they've put a halt to production. Now interesting are 
      robots that are out in the public. These would be on construction sites for
      example. But they are like any construction equipment off-limits to people
      getting in there and fidling with equipment is breaking the law.

So how can these machines become a threat?  One simple thing comes to mind
where one machine is given instructions to modify other machines. It would
have to disable the emergency shutdown and have the system disabled that
helps it accept new commands like making it deaf after giving the machine a
similar command to change the programming of other machines.

I'd always have a human as the top guy on all of this. The scenario where
robots develop the feeling of beeing slaves and fight against their oppressors
is to me very unlikely because why would I implement such capabilities into
a machine that is supposed to vakuum the house and wash and fold the laundry
in the first place. To me robots are usefull because they are not at all human
that means very physical capable with no agency over what they are going to
do. They have electronic brains so they can execute logic but only as good as
their instructions are.

*** jrmiller82

You're right about scenario 1. Maybe better to just 'scare' instead of shoot?

2 has potential, but we need to restructure it a bit into the 5 sentences
i.e. Describe the story setup, three act structure and an endingi.  

For 3, yeah, UPS truck of the future is what I was going for.  Maybe a
hovering UPS truck?

