#+TITLE: Open Science Fiction Novel 01
* Open Science Fiction Novel 01 

Since we don't even know the plot of our story,
we don't have a specific name yet. When we get farther into the plot, we may
change the repository name to reflect the title of the novel.  

* We Need More Contributors

If you know of anyone who would be interested in this project, please try and
get the word out! We'll probably move past stage one in the next month; the
more ideas we have the better we'll be able to move beyond the first stage.
Please, please feel free to post links to this Github repository anywhere you
think will attract contributors. Thanks in advance!

* Short Description 

An open-sourced science-fiction novel written by the community via the
snowflake top-down method.

* Goal of the Project

The goal of this project is to see if it's possible to create a
high-quality community-written science-fiction novel. It will be
written in stages via the [[http://www.advancedfictionwriting.com/articles/snowflake-method/][snowflake method]]. Each stage will be fully
completed before moving on to the next stage of the snowflake.

* Format of the Project

We'll be using org-mode syntax with plain-text files ending in the
".org" suffix. While using emacs makes org-mode more powerful, for the
simple markup needs we need for this project, any plain-text editor
will do. 

Please read the org_quick_tutorial.org file in the repository for a
quick rundown on the syntax. 

And just to be perfectly clear, *you do not have to use Emacs*. You
can use /any/ plain-text editor that you prefer; you can even use
Github's web-based editor. 

Org syntax is important to me in that it makes it wonderfully easy to
export to different formats such as html, latex, pdf, odt, plain text,
etc..

When we get into writing prose, I'll put together a style guide for
everyone to follow that includes both org syntax as well as grammar and other conventions.

* Licensing of the Project

Licensing under the project shall be under the Creative Commons
CC-BY-SA license version 3.0. For further information, please see the
included LICENSE file in the repository. 

* Contributing to the Project

By contributing to the project, each contributor is licensing their
contributions under the same CC-BY-SA license version 3.0 as this main
project. All contributions must be entirely the contributor's original
work and not derived from any other source, even including public
domain information and shall require a typed statement to that effect.
Contributors shall not be anonymous to help enforce this.

* Planned Stages

This section discusses the planned progression of the project
according to the snowflake method. We are currently on the first
stage.

The detailed substeps in each stage still need to be fleshed out. If
anyone has any good ideas, please send me a pull request or submit an
issue please.

1. TODO *Single Sentence Description of the Novel*
   
   *This is our current stage*

   - Approximately 15-word sentence. No character names, think big
     picture. The idea is to get the /very/ basic arc of the story in
     one single sentence.
   
   - These sentences go in the file
     snowflake_stage_01-STORYLINES.org. Try and follow the syntax even
     if you aren't using emacs to write in org-mode format.
    
   - Each contributor shall have a set number of days to vote for
     their favorite three main sentences without any particular
     order. The three sentences that win the initial vote shall be
     subject to a runoff vote with each contributor getting one
     vote. The winning sentence shall be the basis for the novel and
     we'll move forward to the next stage.
     
   - Please see the voting file. *It's now time to vote everybody!*
     
      

2. TODO *Expand the Single Sentence into a full paragraph of 5 sentences*

   Describe the story setup, three act structure and an ending. Think of
   this like three disasters and an ending. Ideally, with the second and
   third disasters caused by the protagonist's attempts to fix things.

3. TODO *One-page Character Sheets on Main Characters*
   
   These sheets are for consistency purposes to get background details
   hammered out before progressing too far.

4. TODO *Expand each sentence of prior paragraph into new 5 sentence paragraph*
   
   Back to the plot. At the end of this we should have 5 new 5
   sentence paragraphs. Please resist the temptation to put in too
   much. We're getting the /big picture/ stuff in line so we know
   /now/ whether there are any problems with the story.

5. TODO *Expand Character sheets for Main characters and synopses and one-pagers on minor characters*
   
   Now we go into much more detail on the characters. Any
   character-specific sub plots, motivations, desires, fears,
   etc.. Again, this is for consitency purposes. 

6. TODO *Full Detail Synopsis, by expanding each sentence of prior into 5 sentences*. 
   
   Back to the plot again, we take the sentences from stage 4 into 5
   sentences each again. 

7. TODO *Use Synopsis to create sheet of chapters / scenes*
   
   We take step 6 and start ordering scenes to march through the
   synopsis. Will need to determine if a table is the best format or
   to use org syntax headings to order the scenes. 

8. TODO *Organize Scenes into Proactive and Reactive*
   
   Scenes are further broken down into proactive scenes and reactive
   scenes. I'll give more detail on this in the future. 

9. TODO *Break Scenes down further*

   Proactive scenes broken down into Goal, Conflict, Setback.

   Reactive scenes broken down into Reaction Dilemma Decision.
   
   I'll give more detail on this in the future. 

10. TODO *Break Scenes down into Motivation Reaction Units*
	
	I'll give more detail on this in the future.

11. TODO *Write Novel according to Motivation Reaction Units*

12. TODO *Technical Editing and Proofreading*

13. TODO *Beta Readers and Revisions*

14. TODO *Release Novel*

15. TODO *If Successful, Repeat!*
