* Snowflake Stage 01 -- Story Lines
This is the file where we'll pick our storylines for the very first
part of the snowflake.

Ideally, I'd like to see /at least/ 10 or 20 story lines before we get into
voting. Ideally we'd have a lot more. And only contributors with accepted pull
requests get to vote come the voting stage.

- [ ] To-do list [0/5]
  - [ ] Get 10-20 story lines
  - [ ] Hold First Vote
	- [ ] Set time limit
	- [ ] Notify contributors of votes
  - [ ] Hold Run-off Vote
	- [ ] Set time limit
	- [ ] Notify contributors of votes
  - [ ] Crown the Winner
  - [ ] Move this file to readonly and proceed to stage 02

** Examples

1. A group of writers come together to create a catching story but may
   be thwarted by interest or technology. 

2. A hobbit learns that he must risk his life to destroy a priceless
   family heirloom to save the world from the Devil. 

** Submissions

1. A space marine must risk destroying Earth to save all of humanity 
   from an alien invasion.

2. A doctor discovers a horrible secret after she is trapped
   aboard a colony ship.

3. After being infected by an alien plague, a regular Joe must choose 
   to save himself or the world. 

4. A hacker must save the world after his prank goes wrong and 
   starts a robot uprising. 

   1. A hacker must save the world after a practical joke inadvertently starts
      a robot uprising.

   2. A hacker must save the world after his practical joke causes robot dogs
      to start killing their owners. 

5. A husband must choose between resurrecting his wife, and burning down 
   NYC. 

6. A detective must overcome his hatred of aliens in order to solve his
   brother's murder. 

** Discussion
Use this section as a placeholder for discussions about story
lines. Please feel free to make many nested sub headings as needed.

*** July 4th, 2014
- I was bored on July 4th and added storylines 1--5. If you want to tweak them
  or riff off of those, please /nest/ them underneath the original story line
  so we can keep similar story lines together.  
   
** TODO First Vote
   Eventual placeholder for voting.
** TODO Runoff Vote
   Eventual placeholder for runoff voting.
** TODO Winning Story Line
   Eventual placeholder for the winner.
