* Snowflake Stage 01 -- Story Lines
This is the file where we'll pick our storylines for the very first
part of the snowflake.

Ideally, I'd like to see 10 or 20 story lines before we get into
voting. And only contributors with accepted pull requests get to vote
come the voting stage.

- [ ] To-do list [0/5]
  - [ ] Get 10-20 story lines
  - [ ] Hold First Vote
	- [ ] Set time limit
	- [ ] Notify contributors of votes
  - [ ] Hold Run-off Vote
	- [ ] Set time limit
	- [ ] Notify contributors of votes
  - [ ] Crown the Winner
  - [ ] Move this file to readonly and proceed to stage 02

** Examples

1. A group of writers come together to create a catching story but may
   be thwarted by interest or technology. 

2. A hobbit learns that he must risk his life to destroy a priceless
   family heirloom to save the world from the Devil. 

** Submissions

1. [first submission here]
   
** Discussion
Use this section as a placeholder for discussions about story
lines. Please feel free to make many nested sub headings as needed.
   
** TODO First Vote
   Eventual placeholder for voting.
** TODO Runoff Vote
   Eventual placeholder for runoff voting.
** TODO Winning Story Line
   Eventual placeholder for the winner.
